### PR TITLE
Remove hardcoded OSX min version

### PR DESCRIPTION
**Pull request by nonhermitian**
Removes the hard coding for OSX min version number.  Can now set via `MACOSX_DEPLOYMENT_TARGET` as suggested by @mtreinish

### CODE REVIEW

**Review by mtreinish — COMMENTED** [review]
I'm a bit confused by this. If apple stop shipping macOS 10.x SDKs on arm systems, what about on intel macs? Like in CI on release we've been building 10.14 binaries for intel macs and the universal2 wheels are tagged as 10.14 but really it's 10.14 for intel and 10.15 for arm64 (as 10.14 didn't support arm64 afaik). This PR is effectively raising that to macOS 11 across the board right? Do you have an idea on what percentage of the install base is on 11 already? Also does this move mean the published pre-compiled universal2 binaries on pypi no longer work on arm64?

That being said I'm wondering if instead of explicitly setting a version in the setup.py we can leverage the `MACOSX_DEPLOYMENT_TARGET` env variable to adjust the target dynamically in the release jobs (which cibuildwheel should be doing for us already) and remove these flags from the `setup.py`. That way for the x86_64 binaries we target an older macOS version but for arm64/universal 2 it's at 11. Also, that way things will work for you locally doing dev on your arm64 mac because we're not explicitly hard coding a version in the setup.py anymore and the compiler will just use the version installed.

**Comment by nonhermitian** [comment]
So yeah they are removed on Intel Macs as well on macos 12.  It seems there is a bug to track OSX 11+ at the moment (https://gs.statcounter.com/macos-version-market-share/desktop/worldwide) however do like the use of the env var to set.

**Comment by nonhermitian** [comment]
This works nicely now on my machines using 

```
CC=clang CXX=clang MACOSX_DEPLOYMENT_TARGET=12 python setup.py build --with-openmp
```

**Comment by nonhermitian** [comment]
@mtreinish when you get a chance.  Not sure if removing the hardcoding on OSX deployment will break the current build process or not.

**Review by mtreinish — APPROVED** [review]
Oh sorry, forgot to circle back to this. Yeah this should be good, `cibuildwheel` will internally set the mac os version support for us: https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#macos-and-deployment-target-versions but if we do need to explicitly set it to something else per release job we can add the deployment target env variable to the ci config: https://github.com/Qiskit-Partners/mthree/blob/main/.github/workflows/release.yml#L30

**Pull request merged**
